version: "3.8"

services:
  server:
    container_name: chat-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - mongo
    command: reflex -r '\.go$$' -s go run .
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env.mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    expose:
      - 8081
    env_file:
      - .env.mongo-client
    depends_on:
      - mongo
