version: "3.8"

services:
  server:
    container_name: chat-server-test
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
    command: go test -v ./...
  mongo:
    image: mongo
    env_file:
      - .env.mongo
